    import geometry; size(7cm,0);
    show(currentcoordsys, xpen=invisible);
    ellipse el=ellipse((2,2),2,1,25);
    draw(el, linewidth(bp));
    real L=arclength(el);
    dot("0", curpoint(el,0), dir(25));
    dot("L/4", curpoint(el,L/4), dir(115));
    dot("3*L/4", curpoint(el,3*L/4), -dir(115));
    dot("-L/2", curpoint(el, -L/2), -dir(25));
    dot("11*L/8", curpoint(el, 11*L/8), dir(145));
    label("L=arclength(el)",(2,0.25));
